### PR TITLE
Bring project up to date

### PR DESCRIPTION
**Pull request by jacobtomlinson**
Trying to bring the project up to date so that development can continue:

- Removed the experimental TUI as it used a very old textual version and lots of things were breaking. This can be reinstated later.
- Bumped Python versions.

### CODE REVIEW

**Comment by davidbrochart** [comment]
@jacobtomlinson I was wondering what was the status of the Textual-based TUI? I see it was removed in this PR, but do you plan to bring it back with the latest Textual?
I'd like to make a [jpterm](https://github.com/davidbrochart/jpterm) plugin for it, something similar to the [JupyterLab Dask extension](https://github.com/dask/dask-labextension). Do you think I could steal the code you removed here, and try to adapt it to the latest Textual?

**Comment by jacobtomlinson** [comment]
@davidbrochart I would love to bring the TUI back, but it is firmly in the category of "side project I would love to work on but don't have time for". 

A plugin for `jpterm` would be amazing. I wonder if we could design things in a way that would allow Dask widgets to be used in both projects one day. I never finished things here, but if you want to grab what I did and adapt it then please go ahead. 

Keep me in the loop and I'll see if I can find time to help out!

**Comment by davidbrochart** [comment]
> @davidbrochart I would love to bring the TUI back, but it is firmly in the category of "side project I would love to work on but don't have time for".

I understand, `jpterm` is actually exactly that kind of project for me :)

> A plugin for `jpterm` would be amazing. I wonder if we could design things in a way that would allow Dask widgets to be used in both projects one day. I never finished things here, but if you want to grab what I did and adapt it then please go ahead.

That would be a great long-term goal, but starting from what you had here might be more approachable for me. I'll definitely let you know if/when I get something working. BTW, I remember you posted some pretty impressive screencasts demoing this TUI, but I cannot find it anymore. I think it was on Twitter, do you have a link to a post by any chance?

**Comment by jacobtomlinson** [comment]
Yeah totally understand.

Maybe this one? https://twitter.com/_JacobTomlinson/status/1559442768983998465

**Comment by davidbrochart** [comment]
Yes, thanks!

**Pull request merged**
